In [5]:
#used to give the linear spacing between the numbers
import numpy as np
numbers = np.linspace(5, 50, 20, dtype=int).reshape(4, -1)
numbers

array([[ 5,  7,  9, 12, 14],
       [16, 19, 21, 23, 26],
       [28, 31, 33, 35, 38],
       [40, 42, 45, 47, 50]])

In [10]:
# conditional array 
mask = numbers % 4 == 0
mask

array([[False, False, False,  True, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False]])

In [11]:
#print true values
numbers[mask]

array([12, 16, 28, 40])

In [13]:
numbers.size

20

In [16]:
#maclauren series
from math import e, factorial

import numpy as np

fac = np.vectorize(factorial)

def e_x(x, terms=10):
    """Approximates e^x using a given number of terms of
    the Maclaurin series
    """
    n = np.arange(terms)
    print(n)
    return np.sum((x ** n) / fac(n))

if __name__ == "__main__":
    print("Actual:", e ** 3)  # Using e from the standard library

    print("N (terms)\tMaclaurin\tError")

    for n in range(1, 14):
        maclaurin = e_x(3, terms=n)
        print(f"{n}\t\t{maclaurin:.03f}\t\t{e**3 - maclaurin:.03f}")

Actual: 20.085536923187664
N (terms)	Maclaurin	Error
[0]
1		1.000		19.086
[0 1]
2		4.000		16.086
[0 1 2]
3		8.500		11.586
[0 1 2 3]
4		13.000		7.086
[0 1 2 3 4]
5		16.375		3.711
[0 1 2 3 4 5]
6		18.400		1.686
[0 1 2 3 4 5 6]
7		19.412		0.673
[0 1 2 3 4 5 6 7]
8		19.846		0.239
[0 1 2 3 4 5 6 7 8]
9		20.009		0.076
[0 1 2 3 4 5 6 7 8 9]
10		20.063		0.022
[ 0  1  2  3  4  5  6  7  8  9 10]
11		20.080		0.006
[ 0  1  2  3  4  5  6  7  8  9 10 11]
12		20.084		0.001
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
13		20.085		0.000


In [26]:
#structered array
data = np.array([
     ("joe", 32, 6),
     ("mary", 15, 20),
     ("felipe", 80, 100),
     ("beyonce", 38, 9001),
], dtype=[("name", str, 10), ("age", int), ("power", int)])
data[0]

('joe', 32, 6)

In [28]:
data["name"]

array(['joe', 'mary', 'felipe', 'beyonce'], dtype='<U10')

In [29]:
data[data["power"] > 9000]["name"]

array(['beyonce'], dtype='<U10')