In [6]:
#np library is imported
import numpy
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [7]:
#printing the array at particular indexes
arr2d[0][2]

3

In [8]:
arr2d[0,2]

3

In [9]:
#2d array
arr3d = numpy.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
#the tupple at 0th index is printed
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
#copy the old array
old_values = arr3d[0].copy()
arr3d[0]=42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [13]:
arr3d[1,0]

array([7, 8, 9])

In [14]:
#:2 means from 0 till 2 but not 2
#1: means from 1 till the last element
#arr[array set of element , particular element from the set]
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [15]:
#without : value means only from particular set
arr2d[1,:2]

array([4, 5])

In [16]:
arr2d[2,:1]

array([7])

In [17]:
# no : means from 0 till last
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [18]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [19]:
#working with boolean indexing
names = numpy.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = numpy.random.randn(7,4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [20]:
data

array([[ 1.12728891,  1.80853668, -1.15833111, -0.66964837],
       [ 0.55359145, -1.26972892, -0.34905707,  0.03856003],
       [-0.77869169, -0.37108522,  1.30119779, -0.57923828],
       [ 0.77132404, -0.60241425, -0.09500483, -1.49578635],
       [ 1.8876628 ,  1.43057833,  1.03957199,  0.34536916],
       [ 1.23553173, -0.4710111 , -0.40359379, -0.08261751],
       [ 1.70434802,  0.01481884,  0.13518465,  0.01364942]])

In [21]:
names =='Bob'

array([ True, False, False,  True, False, False, False])

In [22]:
data[names=='Bob']

array([[ 1.12728891,  1.80853668, -1.15833111, -0.66964837],
       [ 0.77132404, -0.60241425, -0.09500483, -1.49578635]])

In [23]:
data[names == 'Bob', 2:]

array([[-1.15833111, -0.66964837],
       [-0.09500483, -1.49578635]])

In [24]:
data[names=='Bob',3]

array([-0.66964837, -1.49578635])

In [25]:
 names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [26]:
data[~(names == 'Bob')]

array([[ 0.55359145, -1.26972892, -0.34905707,  0.03856003],
       [-0.77869169, -0.37108522,  1.30119779, -0.57923828],
       [ 1.8876628 ,  1.43057833,  1.03957199,  0.34536916],
       [ 1.23553173, -0.4710111 , -0.40359379, -0.08261751],
       [ 1.70434802,  0.01481884,  0.13518465,  0.01364942]])

In [27]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [28]:
data[mask]

array([[ 1.12728891,  1.80853668, -1.15833111, -0.66964837],
       [-0.77869169, -0.37108522,  1.30119779, -0.57923828],
       [ 0.77132404, -0.60241425, -0.09500483, -1.49578635],
       [ 1.8876628 ,  1.43057833,  1.03957199,  0.34536916]])

In [30]:
data[data < 0] = 0
data

array([[1.12728891, 1.80853668, 0.        , 0.        ],
       [0.55359145, 0.        , 0.        , 0.03856003],
       [0.        , 0.        , 1.30119779, 0.        ],
       [0.77132404, 0.        , 0.        , 0.        ],
       [1.8876628 , 1.43057833, 1.03957199, 0.34536916],
       [1.23553173, 0.        , 0.        , 0.        ],
       [1.70434802, 0.01481884, 0.13518465, 0.01364942]])

In [31]:
data[names!='Joe']=7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.55359145, 0.        , 0.        , 0.03856003],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.23553173, 0.        , 0.        , 0.        ],
       [1.70434802, 0.01481884, 0.13518465, 0.01364942]])

In [32]:
arr = numpy.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [33]:
#empty is used to make the new empty array of the desired size
arr = numpy.empty((8, 4))

In [34]:
for i in range(8):
    arr[i]=i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [35]:
#assigining the values to array and print
arr[[4, 3, 0, 6]]


array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [36]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [37]:
#a-range is used to arrange the elemens in the array or list
arr = numpy.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [38]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]


array([ 4, 23, 29, 10])

In [39]:
#Transposing Arrays and Swapping Axes

arr = numpy.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [40]:
#transpose
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [41]:
#inner matrix product XTX using numpy.dot
arr = numpy.random.randn(6, 3)
numpy.dot(arr.T,arr)

array([[10.31735948,  2.22482051,  0.34933817],
       [ 2.22482051,  3.45001955, -0.5150379 ],
       [ 0.34933817, -0.5150379 ,  4.83175963]])

In [42]:
arr=numpy.arange(16).reshape(2,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [43]:
#transpose
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [44]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [45]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [46]:
#finding square root of the array elements
arr=numpy.arange(10)
numpy.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [47]:
numpy.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [48]:
#assigining random values to x and y
x=numpy.random.randn(8)
y=numpy.random.randn(8)
x

array([-1.28634964,  0.44400344,  1.68698322,  0.038719  ,  0.85085221,
       -2.80145652, -1.41583982, -0.72385564])

In [49]:
y

array([ 0.57676786, -1.31254058, -0.12021011, -0.6084725 , -0.13688285,
        0.47986376, -0.26875429, -1.56240126])

In [50]:
#element wise maximum values from x and y
numpy.maximum(x,y)

array([ 0.57676786,  0.44400344,  1.68698322,  0.038719  ,  0.85085221,
        0.47986376, -0.26875429, -0.72385564])

In [53]:
arr=numpy.random.randn(7)*5


In [57]:
arr

array([  0.89536636,   1.42785422,  -8.36244168,   8.91172791,
       -10.08609646,  -1.04820054,  -2.58590913])

In [54]:
numpy.modf(arr)

(array([ 0.89536636,  0.42785422, -0.36244168,  0.91172791, -0.08609646,
        -0.04820054, -0.58590913]),
 array([  0.,   1.,  -8.,   8., -10.,  -1.,  -2.]))

In [58]:
#to found the sign of the number
numpy.sign(arr)

array([ 1.,  1., -1.,  1., -1., -1., -1.])

In [64]:
import numpy as np
arrt=np.multiply(arr,arr)
arrt

array([  0.80168092,   2.03876767,  69.93043088,  79.41889442,
       101.72934188,   1.09872437,   6.68692604])

In [69]:
np.greater(arrt,arr)

array([False,  True,  True,  True,  True,  True,  True])

In [74]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([1.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result=np.where(xarr==yarr,xarr,yarr)
result

array([1.1, 2.2, 2.3, 2.4, 2.5])

In [77]:
arr =np.random.randn(4, 4)
arr

array([[-0.71874551, -0.36639939,  0.59822174, -0.34336688],
       [ 0.35867793,  0.55508358,  0.75102013, -0.48855097],
       [ 0.28542192, -0.78153063, -1.86203785, -1.35025002],
       [ 0.49218225,  0.31039978, -0.92155989, -0.710207  ]])

In [78]:
np.where(arr > 0, 2, -2)


array([[-2, -2,  2, -2],
       [ 2,  2,  2, -2],
       [ 2, -2, -2, -2],
       [ 2,  2, -2, -2]])

In [80]:
np.where(arr > 0, 2, arr) 

array([[-0.71874551, -0.36639939,  2.        , -0.34336688],
       [ 2.        ,  2.        ,  2.        , -0.48855097],
       [ 2.        , -0.78153063, -1.86203785, -1.35025002],
       [ 2.        ,  2.        , -0.92155989, -0.710207  ]])

In [107]:
arr = np.arange(32).reshape(8,4)
arr[0,0]=1
arr

array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [108]:
arr.mean()

15.53125

In [109]:
arr.cumprod()

array([          1,           1,           2,           6,          24,
               120,         720,        5040,       40320,      362880,
           3628800,    39916800,   479001600,  1932053504,  1278945280,
        2004310016,  2004189184,  -288522240,  -898433024,   109641728,
       -2102132736, -1195114496,  -522715136,   862453760,  -775946240,
        2076180480, -1853882368,  1484783616, -1375731712, -1241513984,
        1409286144,   738197504], dtype=int32)

In [112]:
arr

array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [113]:
#number of values greater than 5
(arr>5).sum()

26

In [119]:
bools = np.array([1, 0, True,1])
print(bools.any()) 
#returns true if any the values are true 
bools.all() 
#returns true if all the values are true

True


False

# Sorting

In [128]:
arr=np.random.randn(3,4)
print(arr,'\n\n\n')
arr.sort()
arr

[[-1.47283657  2.06284773 -0.38384748  0.54600974]
 [ 0.84164686  0.71984622  1.2499588  -0.82652284]
 [-1.73729735 -0.13596887  0.07457823  0.80876853]] 





array([[-1.47283657, -0.38384748,  0.54600974,  2.06284773],
       [-0.82652284,  0.71984622,  0.84164686,  1.2499588 ],
       [-1.73729735, -0.13596887,  0.07457823,  0.80876853]])

In [129]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [132]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [133]:
list1 = [1,2,4,5,1,3,6,7]  #unbsorted
list2 = sorted(list1) #list1 sorted in--> list2
print(list1) #list1 is still unsorted
print(list2) #sorted list
list1.sort() #list1 is sorted
list1

[1, 2, 4, 5, 1, 3, 6, 7]
[1, 1, 2, 3, 4, 5, 6, 7]


[1, 1, 2, 3, 4, 5, 6, 7]

a=[1,2,3,4]
b=[1,5,6,7]
2,3,4,5,6,7--> setxor1d(a,b)
2,3,4 --> setdiff1d(a,b)
